### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by jameqq** [aipeach/SSPanelSubcribe#2]
PHP Fatal error:  Uncaught Exception: config file : /www/wwwroot/www.xxx/dev.php is miss in /www/wwwroot/www.xxx/vendor/easyswoole/easyswoole/src/Config.php:101
Stack trace:
#0 /www/wwwroot/www.xxx/vendor/easyswoole/easyswoole/src/Core.php(294): EasySwoole\EasySwoole\Config->loadEnv()
#1 /www/wwwroot/www.xxx/vendor/easyswoole/easyswoole/src/Core.php(100): EasySwoole\EasySwoole\Core->loadEnv()
#2 /www/wwwroot/www.xxx/vendor/easyswoole/easyswoole/src/Command/CommandRunner.php(49): EasySwoole\EasySwoole\Core->initialize()
#3 /www/wwwroot/wwwxxx/easyswoole(45): EasySwoole\EasySwoole\Command\CommandRunner->run()
#4 {main}
  thrown in /www/wwwroot/www.xxx/vendor/easyswoole/easyswoole/src/Config.php on line 101
提示这个怎么解决 请问下

**Comment by aipeach** [comment]
> 

dev.php有没有？

**Comment by jameqq** [comment]
produce.php，填好设置就行了？宝塔要其他设置吗 SSL？

**Comment by aipeach** [comment]
> produce.php，填好设置就行了？宝塔要其他设置吗 SSL？

用produce 启动看这个 https://www.easyswoole.com/QuickStart/command.html
SSL用nginx搞，/link 反代订阅服务即可
